### ISSUE TITLE
Ocean.assets.search() method crashes for certain keywords and addresses (on Mumbai)

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/ocean.py#1037] opened 2022-10-21 13:58 UTC
**Describe the bug**
The ocean.asset.search() method crashes with the code Keyerror: 'id' when searching for 'NFTs' or for address '0x00Dc9e712D3b31Ab5446A5A7CeaDe0a2901E6d26', on Mumbai network.

**To Reproduce**

In the system console:

```
python
```

In the python console:
```
>>> import os
>>> from ocean_lib.example_config import ExampleConfig
>>> from ocean_lib.ocean.ocean import Ocean
>>> config = ExampleConfig.get_config("https://matic-mumbai.chainstacklabs.com")
>>> config["BLOCK_CONFIRMATIONS"] = 1 #faster
>>> ocean = Ocean(config)
>>> ocean.config_dict
{'RPC_URL': 'https://matic-mumbai.chainstacklabs.com', 'BLOCK_CONFIRMATIONS': 1, 'TRANSACTION_TIMEOUT': 60, 'METADATA_CACHE_URI': 'https://v4.aquarius.oceanprotocol.com', 'PROVIDER_URL': 'https://v4.provider.mumbai.oceanprotocol.com', 'DOWNLOADS_PATH': 'consume-downloads'}

>>> #testing with "NTFs"
>>> ocean.assets.search("NFTs")
INFO:ocean:Searching asset containing: NFTs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 710, in search
    return [
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 711, in <listcomp>
    Asset.from_dict(ddo_dict["_source"])
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/assets/asset.py", line 101, in from_dict
    values.pop("id"),
KeyError: 'id'

>>> #testing with another keyword works just fine
>>>ocean.assets.search("Data")
INFO:ocean:Searching asset containing: Data
[<ocean_lib.assets.asset.Asset object at 0x7f665eabdc40>, <ocean_lib.assets.asset.Asset object at 0x7f665eabda00>, <ocean_lib.assets.asset.Asset object at 0x7f665eabda30>, <ocean_lib.assets.asset.Asset object at 0x7f665eabdd30>, <ocean_lib.assets.asset.Asset object at 0x7f665eabda90>, <ocean_lib.assets.asset.Asset object at 0x7f665eabdf70>, <ocean_lib.assets.asset.Asset object at 0x7f665eabd7c0>, <ocean_lib.assets.asset.Asset object at 0x7f665eabdee0>, <ocean_lib.assets.asset.Asset object at 0x7f665eabdcd0>, <ocean_lib.assets.asset.Asset object at 0x7f665eabdd90>]

>>>#testing with the address "0x00Dc9e712D3b31Ab5446A5A7CeaDe0a2901E6d26"
>>> ocean.assets.search("0x00Dc9e712D3b31Ab5446A5A7CeaDe0a2901E6d26")
INFO:ocean:Searching asset containing: 0x00Dc9e712D3b31Ab5446A5A7CeaDe0a2901E6d26
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 710, in search
    return [
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 711, in <listcomp>
    Asset.from_dict(ddo_dict["_source"])
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/assets/asset.py", line 101, in from_dict
    values.pop("id"),
KeyError: 'id'

>>>#testing with another address ("0xD65Cdba4b7Ea5A40f0Cc1F1CbB076De5DC64Fe6f") works just fine
>>> ocean.assets.search("0xD65Cdba4b7Ea5A40f0Cc1F1CbB076De5DC64Fe6f")
INFO:ocean:Searching asset containing: 0xD65Cdba4b7Ea5A40f0Cc1F1CbB076De5DC64Fe6f
[<ocean_lib.assets.asset.Asset object at 0x7f665eabd700>, <ocean_lib.assets.asset.Asset object at 0x7f665eabd790>, <ocean_lib.assets.asset.Asset object at 0x7f665eabde20>, <ocean_lib.assets.asset.Asset object at 0x7f665eabda90>, <ocean_lib.assets.asset.Asset object at 0x7f665eabda30>, <ocean_lib.assets.asset.Asset object at 0x7f665eabdfd0>, <ocean_lib.assets.asset.Asset object at 0x7f665eabddc0>, <ocean_lib.assets.asset.Asset object at 0x7f665eabda00>, <ocean_lib.assets.asset.Asset object at 0x7f665eabd7c0>, <ocean_lib.assets.asset.Asset object at 0x7f665eabdc40>]
>>>
```

**Expected behavior**
ocean.assets.search() returns the results for keyword "NFTs" or for address "0x00Dc9e712D3b31Ab5446A5A7CeaDe0a2901E6d26"

**Desktop (please complete the following information):**
OS: Ubuntu Linux 22.04
ocean.py 1.6.1

**Additional context**
Note that all assets that contain the word "NFTs" belong to address "0x00Dc9e712D3b31Ab5446A5A7CeaDe0a2901E6d26".

**Comment by MBadea17** [comment] 2022-10-25 13:49
Also, in the same environment as described above, for certain DIDs, ocean.assets.search() returns the following output:
```
>>> results3 = ocean.assets.search("did:op:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489")
INFO:ocean:Searching asset containing: did:op:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 712, in search
    for ddo_dict in self._aquarius.query_search(
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/aquarius/aquarius.py", line 124, in query_search
    raise ValueError(f"Unable to search for DDO: {response.content}")
ValueError: Unable to search for DDO: b'{"error":"search_phase_execution_exception","info":{"error":{"caused_by":{"reason":"parse_exception: Encountered \\" \\":\\" \\": \\"\\" at line 1, column 6.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\"+\\" ...\\n    \\"-\\" ...\\n    <BAREOPER> ...\\n    \\"(\\" ...\\n    \\"*\\" ...\\n    \\"^\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\"[\\" ...\\n    \\"{\\" ...\\n    <NUMBER> ...\\n    ","type":"parse_exception"},"failed_shards":[{"index":"aquarius","node":"-TMmxVkxQNi6VhlXMqJXcg","reason":{"caused_by":{"caused_by":{"reason":"parse_exception: Encountered \\" \\":\\" \\": \\"\\" at line 1, column 6.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\"+\\" ...\\n    \\"-\\" ...\\n    <BAREOPER> ...\\n    \\"(\\" ...\\n    \\"*\\" ...\\n    \\"^\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\"[\\" ...\\n    \\"{\\" ...\\n    <NUMBER> ...\\n    ","type":"parse_exception"},"reason":"parse_exception: Cannot parse \'did:op:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489\': Encountered \\" \\":\\" \\": \\"\\" at line 1, column 6.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\"+\\" ...\\n    \\"-\\" ...\\n    <BAREOPER> ...\\n    \\"(\\" ...\\n    \\"*\\" ...\\n    \\"^\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\"[\\" ...\\n    \\"{\\" ...\\n    <NUMBER> ...\\n    ","type":"parse_exception"},"index":"aquarius","index_uuid":"Y2xZ7V68ThaAMTiW7CB9og","reason":"Failed to parse query [did:op:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489]","type":"query_shard_exception"},"shard":0},{"index":"aquarius_plus","node":"G1Oi1vlmS7CGiZVRjn80jw","reason":{"caused_by":{"caused_by":{"reason":"Encountered \\" \\":\\" \\": \\"\\" at line 1, column 6.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\"+\\" ...\\n    \\"-\\" ...\\n    <BAREOPER> ...\\n    \\"(\\" ...\\n    \\"*\\" ...\\n    \\"^\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\"[\\" ...\\n    \\"{\\" ...\\n    <NUMBER> ...\\n    ","type":"parse_exception"},"reason":"Cannot parse \'did:op:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489\': Encountered \\" \\":\\" \\": \\"\\" at line 1, column 6.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\"+\\" ...\\n    \\"-\\" ...\\n    <BAREOPER> ...\\n    \\"(\\" ...\\n    \\"*\\" ...\\n    \\"^\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\"[\\" ...\\n    \\"{\\" ...\\n    <NUMBER> ...\\n    ","type":"parse_exception"},"index":"aquarius_plus","index_uuid":"KttvhXXGQjaSld7LfsfOWA","reason":"Failed to parse query [did:op:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489]","type":"query_shard_exception"},"shard":0},{"index":"aquarius_retries","node":"-TMmxVkxQNi6VhlXMqJXcg","reason":{"caused_by":{"caused_by":{"reason":"parse_exception: Encountered \\" \\":\\" \\": \\"\\" at line 1, column 6.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\"+\\" ...\\n    \\"-\\" ...\\n    <BAREOPER> ...\\n    \\"(\\" ...\\n    \\"*\\" ...\\n    \\"^\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\"[\\" ...\\n    \\"{\\" ...\\n    <NUMBER> ...\\n    ","type":"parse_exception"},"reason":"parse_exception: Cannot parse \'did:op:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489\': Encountered \\" \\":\\" \\": \\"\\" at line 1, column 6.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\"+\\" ...\\n    \\"-\\" ...\\n    <BAREOPER> ...\\n    \\"(\\" ...\\n    \\"*\\" ...\\n    \\"^\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\"[\\" ...\\n    \\"{\\" ...\\n    <NUMBER> ...\\n    ","type":"parse_exception"},"index":"aquarius_retries","index_uuid":"dbb_W1wYQaS3KWYO-c1xYg","reason":"Failed to parse query [did:op:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489]","type":"query_shard_exception"},"shard":0}],"grouped":true,"phase":"query","reason":"all shards failed","root_cause":[{"reason":"parse_exception: Encountered \\" \\":\\" \\": \\"\\" at line 1, column 6.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\"+\\" ...\\n    \\"-\\" ...\\n    <BAREOPER> ...\\n    \\"(\\" ...\\n    \\"*\\" ...\\n    \\"^\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\"[\\" ...\\n    \\"{\\" ...\\n    <NUMBER> ...\\n    ","type":"parse_exception"},{"index":"aquarius_plus","index_uuid":"KttvhXXGQjaSld7LfsfOWA","reason":"Failed to parse query [did:op:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489]","type":"query_shard_exception"},{"reason":"parse_exception: Encountered \\" \\":\\" \\": \\"\\" at line 1, column 6.\\nWas expecting one of:\\n    <EOF> \\n    <AND> ...\\n    <OR> ...\\n    <NOT> ...\\n    \\"+\\" ...\\n    \\"-\\" ...\\n    <BAREOPER> ...\\n    \\"(\\" ...\\n    \\"*\\" ...\\n    \\"^\\" ...\\n    <QUOTED> ...\\n    <TERM> ...\\n    <FUZZY_SLOP> ...\\n    <PREFIXTERM> ...\\n    <WILDTERM> ...\\n    <REGEXPTERM> ...\\n    \\"[\\" ...\\n    \\"{\\" ...\\n    <NUMBER> ...\\n    ","type":"parse_exception"}],"type":"search_phase_execution_exception"},"status":400}}\n'
```

Not sure if it's the same root cause, let me know if you want me to open a separate issue for this.

**Comment by calina-c** [comment] 2022-11-01 12:49
I don't think that the search fails, it seems to fail from where it converts search results into Asset objects. It seems the search for "NFTs" has some assets that are differently shaped, or something of the likes. I can look into it.

For the other issue, the one searching for "did:op:..." I'm curious @MBadea17 if you search anything that contains the colon symbol, does it work? It seems to be an encoding issue where we communicate with Aquarius.

**Comment by calina-c** [comment] 2022-11-01 13:23
@MBadea17 for the second issue, I confirmed it is an issue with escaping the colon. "did\\:op\\:e552482076da421ccb63972d8323720924b53d4b078c7370a00d759bdb458489" should work perfectly. Where should the responsibility to escape special characters rely? I can add it in the search function, but I'm not sure I should. Tagging @trentmc here as well, he should have some input here as well.

**Comment by calina-c** [comment] 2022-11-01 13:32
For the first issue, the problematic asset can be found using ```{"query": {"query_string": {"query": "0xB4caBc2066e7c22c0316Ac3aBd5EdaBd91aEfeBe"}}}``` and the result should have the `id` key inside `_source`. However, it is missing. We are currently investigating :) it might be some sanitization, or we have "lost" that key somehow. "id" is required by the shacl validation, so it should not be missing (unless we've done something stupid with it).

**Comment by trentmc** [comment] 2022-11-01 14:22
> Where should the responsibility to escape special characters rely? I can add it in the search function, but I'm not sure I should.

Options:
1. ocean.py expects the `\` in front of `:`, raises hard-to-understand error if not met (status quo)
2. ocean.py expects the `\` in front of `:`, raises easy-to-understand error if not met
3. ocean.py expects _no_  `\` in front of `:`, and auto-inserts it. Raises easy-to-understand error if not net
4. ocean.py auto-inserts the `\` in front of `:` if it's not there. 

Analysis:
- (2) is better than (1)
- (3) and (4) are each munging the input a bit. It it's gonna munge, it should munge to avoid errors. Therefore (4) is better than (3).
- This leaves us with (2) and (4). They each have pros and cons, both around developer experience (DX). (2) DX is good in that there's no munging, bad in that it's not obvious to developers that the `:` should be escaped that way. (4) has munging, but beyond that the DX is nice. 

I lean to (4), because best DX. Though if we did (2) that's ok too.

**Comment by calina-c** [comment] 2022-11-05 07:51
@MBadea17 this is fixed in the `main-brownie` branch. Trent recommended to save the effort and not recopy it in main. I would close this ticket, but it depends on the definition of done. Since you (Mihai) reported it, I'm deferring to you.

**Comment by MBadea17** [comment] 2022-11-07 08:37
@calina-c , agree with you to close the issue and include the fix in the new release.

**Closed** 2022-11-08 13:55 UTC
Labels: Type: Bug
