### ISSUE TITLE
Exception raised randomly: Address not found for network_name=development. 

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#1329] opened 2023-02-15 12:39 UTC
From a recent [CI run](https://github.com/oceanprotocol/ocean.py/actions/runs/4183486056/jobs/7247898911#step:8:20), this error occurred randomly which says that if cannot find the addresses development network.

**Solution**
Implement a retry mechanism for this issue.

**Comment by calina-c** [comment] 2023-02-16 10:36
Duplicate of #1259

**Closed by calina-c** 2023-02-16 10:37 UTC
