### ISSUE TITLE
Problem connecting with mumbai testnet

### ISSUE THREAD

**Issue by akshay-ap** [oceanprotocol/ocean.py#891] opened 2022-08-08 13:06 UTC
**Describe the bug**
Faced an issue while using ocean.py with mumbai testnet ([here](https://github.com/oceanprotocol/docs/issues/1096)).
The fix is [here](https://github.com/oceanprotocol/docs/pull/1097) but, would it be possible to apply the fix in ocean.py itself?

The issue might be reproducible for polygon mainnet (needs further testing).

**To Reproduce**
1. Try using ocean.py with mumbai testnet

Logs already copied at https://github.com/oceanprotocol/docs/issues/1096

**Expected behavior**
No issue in interacting with any supported networks using ocean.py.

**Screenshots**
NA
**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by AnaLoznianu** [comment] 2022-08-23 09:08
This is fixed by increasing the number of workers to 4

**Comment by akshay-ap** [comment] 2022-08-30 11:13
Opening the issue again as discussed.

**Comment by AnaLoznianu** [comment] 2022-09-02 10:11
@calina-c After discussing with Akshay, we realised that the problem is not related to the number of workers.

**Comment by trentmc** [comment] 2022-09-17 19:53
I re-discovered this issue in #920.

I fixed that issue (and therefore this one) as part of 
https://github.com/oceanprotocol/ocean.py/commit/a4fb91153891e2b68be90d4a5a7558bbb44e14d4

It's the changes in util.py

**Closed by trentmc** 2022-09-17 19:53 UTC
Labels: Type: Bug
