### ISSUE TITLE
Checking the balance of a datatoken not working `BadFunctionCallOutput`

### ISSUE THREAD

**Issue by smejak** [oceanprotocol/ocean.py#896] opened 2022-08-15 08:18 UTC
**Describe the bug**
I am trying to check the balance of a datatoken in ocean.py with `pretty_ether_and_wei(data_token.balanceOf(address))` and am getting the following error:
```
BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
```
I am using a wallet address on rinkeby and my ocean config is using an infura network endpoint.

**To Reproduce**
1. Configure ocean with `config.ini` for rinkeby v4
```
[eth-network]
network = https://rinkeby.infura.io/v3/insert_api_key
block_confirmations = 0

[resources]
metadata_cache_uri = https://v4.aquarius.oceanprotocol.com
provider.url = https://v4.provider.rinkeby.oceanprotocol.com/
provider.address = 0x00c6A0BC5cD0078d6Cd0b659E8061B404cfa5704
downloads.path = consume-downloads
```
2. run the following code
```
from web3 import Web3
from ocean_lib.config import Config
from ocean_lib.ocean.ocean import Ocean
from ocean_lib.web3_internal.currency import pretty_ether_and_wei

config = Config('./config.ini')
ocean = Ocean(config)

user_address = "insert_your_wallet_address"
address = Web3.toChecksumAddress(user_address)

data_token = ocean.get_datatoken('0xFE2A5155d2A1C8ee3EA4188c9F5253CEC153075C') # can use any other datatoken address
pretty_ether_and_wei(data_token.balanceOf(address))
```
7. See error

**Expected behavior**
Show the balance of the datatoken at the specified wallet address.

**Desktop (please complete the following information):**
 - OS: macOS 12.3

**Comment by mariacarmina** [comment] 2022-08-24 11:07
Hello @smejak, I followed your steps and I couldn't reproduce your issue. I would suggest to try this config.ini file
```
[eth-network]

network = https://rinkeby.infura.io/v3/insert_api_key
address.file = ~/.ocean/ocean-contracts/artifacts/address.json
block_confirmations = 0


[resources]
metadata_cache_uri = https://v4.aquarius.oceanprotocol.com
provider.url = https://v4.provider.rinkeby.oceanprotocol.com/
provider.address = 0x00c6A0BC5cD0078d6Cd0b659E8061B404cfa5704

downloads.path = consume-downloads
```
But from my side it worked perfectly without specifying the address file.
This is my console output
```bash
(venv) maria@ubuntu:~/Desktop/ocean.py$ cat scriptix.py 
from web3 import Web3
from ocean_lib.config import Config
from ocean_lib.ocean.ocean import Ocean
from ocean_lib.web3_internal.currency import pretty_ether_and_wei

config = Config('new_config.ini')
ocean = Ocean(config)

user_address = '0xe2DD09d719Da89e5a3D0F2549c7E24566e947260'
address = Web3.toChecksumAddress(user_address)

data_token = ocean.get_datatoken('0x866B75e6C22e6CfAeC536016DD4F2aE7A1b20b2c') # can use any other datatoken address
print(pretty_ether_and_wei(data_token.balanceOf(address)))
(venv) maria@ubuntu:~/Desktop/ocean.py$ python3 scriptix.py 
0 (0 wei)
```
OS: I have run on a virtual machine wihich has Ubuntu 20.04.

**Comment by AnaLoznianu** [comment] 2022-08-29 07:57
@smejak Do you still have this issue?

**Comment by AnaLoznianu** [comment] 2022-09-20 09:58
I am closing this. If you encounter the issue again, please reopen it

**Closed by AnaLoznianu** 2022-09-20 09:58 UTC
Labels: Type: Bug
