### ISSUE TITLE
Consume flow for onchain assets ends with TypeError

### ISSUE THREAD

**Issue by MBadea17** [oceanprotocol/ocean.py#1031] opened 2022-10-20 13:21 UTC
**Describe the bug**
Running ocean.assets.download_file() for accessing an onchain asset ends with error "TypeError: Expected type '<class 'str'>' for attribute 'file_name' but received type '<class 'NoneType'>')" .

**To Reproduce**
Setup ocean.py and create the two wallets: alice_wallet and bob_wallet.
In the same python console:
```
from ocean_lib.ocean.util import get_address_of_type
name = "swapOceanFee function call - 5"
contract_address = get_address_of_type(config, "Router")
contract_abi = {'inputs': [], 'name': 'swapOceanFee', 'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}], 'stateMutability': 'view', 'type': 'function'}

#create asset
(data_nft, datatoken, asset) = ocean.assets.create_onchain_asset(name, contract_address, contract_abi, alice_wallet)

#Alice gives Bob access
to_address = bob_wallet.address
amt_tokens = ocean.to_wei(10)
datatoken.mint(to_address, amt_tokens, alice_wallet)

# Bob sends a datatoken to the service to get access; then downloads
file_name = ocean.assets.download_file(asset.did, bob_wallet)
Resolve did...
Order access...
INFO:ocean_lib.data_provider.data_service_provider:Service initialized successfully initializeEndpoint https://v4.provider.mumbai.oceanprotocol.com/api/services/initialize
Download file...
INFO:ocean_lib.data_provider.fileinfo_provider:Retrieved asset files successfully FileInfoEndpoint https://v4.provider.mumbai.oceanprotocol.com/api/services/fileinfo from did did:op:b58b542bca6e5cee579f0a3dbef2985dbb0466011afe810be46b915a4c89c588 with service id 0
signing message with nonce 1666259995.576958: did:op:b58b542bca6e5cee579f0a3dbef2985dbb0466011afe810be46b915a4c89c588, account=0xD727FB9Be39fA019d7C02fea19E54d688Da3a662
WARNING:ocean_lib.data_provider.base:It was not possible to get the file name. Expected type '<class 'str'>' for attribute 'header' but received type '<class 'NoneType'>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 775, in download_file
    file_path = self.download_asset(asset, wallet, "./", order_tx_id)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/ocean/ocean_assets.py", line 802, in download_asset
    return download_asset_files(
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/assets/asset_downloader.py", line 73, in download_asset_files
    data_provider.download(
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/ocean_lib/data_provider/data_service_provider.py", line 190, in download
    DataServiceProvider.write_file(response, destination_folder, file_name)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 28, in wrapper
    check_types(*args, **kwargs)
  File "/home/mihai/my_project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 21, in check_types
    raise TypeError(
TypeError: Expected type '<class 'str'>' for attribute 'file_name' but received type '<class 'NoneType'>')

```

**Expected behavior**
The results file is dowloaded to the local system, in the current directory.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 22.04
 - ocean.py 1.6.1

**Comment by MBadea17** [comment] 2022-10-20 19:02
The network I tested on was Mumbai. I followed the steps referenced in the [Publish & Consume Flow using onchain data source](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/publish-flow-onchain.md), specifically the following:

**Set envvars**
In the console:
```
export REMOTE_TEST_PRIVATE_KEY1=<private_key1>
export REMOTE_TEST_PRIVATE_KEY2=<private_key2>
```

**Setup in Python**
In the same console:
```
python
```
In the python console:
```
import os
from ocean_lib.example_config import ExampleConfig
from ocean_lib.ocean.ocean import Ocean
config = ExampleConfig.get_config("https://matic-mumbai.chainstacklabs.com")
config["BLOCK_CONFIRMATIONS"] = 1
ocean = Ocean(config)

# Create Alice's wallet
import os
from ocean_lib.web3_internal.wallet import Wallet

alice_private_key = os.getenv('REMOTE_TEST_PRIVATE_KEY1')
alice_wallet = Wallet(ocean.web3, alice_private_key, config["BLOCK_CONFIRMATIONS"], config["TRANSACTION_TIMEOUT"])
assert alice_wallet.web3.eth.get_balance(alice_wallet.address) > 0, "Alice needs MATIC"
print("Alice wallet created. Wallet address:", alice_wallet.address)

# Create Bob's wallet. While some flows just use Alice wallet, it's simpler to do all here.
bob_private_key = os.getenv('REMOTE_TEST_PRIVATE_KEY2')
bob_wallet = Wallet(ocean.web3, bob_private_key, config["BLOCK_CONFIRMATIONS"], config["TRANSACTION_TIMEOUT"])
assert bob_wallet.web3.eth.get_balance(bob_wallet.address) > 0, "Bob needs MATIC"
print("Bob wallet created. Wallet address:", bob_wallet.address)
```

**Comment by calina-c** [comment] 2022-11-05 07:49
@MBadea17 are you testing with a released version or a branch of ocean.py? If testing with a branch, are you using `main` or `main-brownie`?

https://github.com/oceanprotocol/ocean.py/issues/1053 seems to be a duplicate of this issue and it is now closed. Testing using either branch should work now. For a release, it's trickier since I don't know exactly when we are releasing a new version.

**Comment by MBadea17** [comment] 2022-11-07 08:36
@calina-c , I was testing it with the released version of ocean.py.

**Comment by calina-c** [comment] 2022-11-08 13:57
Fixed after the rename of `main-brownie` to `main` and release of 2.0.0 alpha

**Closed by calina-c** 2022-11-08 13:57 UTC
Labels: Type: Bug
