### ISSUE TITLE
Update to latest web3.py v5

### ISSUE THREAD

**Issue by annonymmous** [oceanprotocol/ocean.py#77] opened 2020-12-03 17:15 UTC
The path for the web3 utils has changed from:

web3.py/web3/utils/ to web3.py/web3/_utils/

accordingly the following ocean_lib modules for Python 3 are broken:

/usr/local/lib/python3.8/dist-packages/ocean_lib/models/data_token.py
/usr/local/lib/python3.8/dist-packages/ocean_lib/web3_internal/contract_base.py
/usr/local/lib/python3.8/dist-packages/ocean_lib/web3_internal/web3_overrides/request.py
/usr/local/lib/python3.8/dist-packages/ocean_lib/models/bpool.py

**Comment by ssallam** [comment] 2021-01-27 12:28
This is not a bug. The user is trying to use a newer web3 version. 
Resolving th is issue requires upgrading ocean.py to use the newer version of web3.

**Comment by kremalicious** [comment] 2021-02-01 20:42
we should not force developers into using multiple-year-old versions of dependencies. web3.py v5 is out for almost 2 years, yet we are still running here with web3.py v4.7.1, released in Sept. 2018. So we really should update to latest version of web3 library, just like ocean.js does

**Comment by DMats** [comment] 2021-04-16 18:03
While I was working on https://github.com/oceanprotocol/ocean.py/issues/228 I ran into the fact that we're using Web3.py v4 instead of v5. This means that I must continue using the deprecated `ConciseContract` calling convention instead of the `ContractCaller`.

**Comment by DMats** [comment] 2021-05-25 17:53
The latest version of Web3.py on PyPi is 5.19.0 so this is what I've instructed @mariacarmina to upgrade to.

**Closed** 2021-05-31 07:42 UTC
Labels: bug, good first issue, priority:high
