### ISSUE TITLE
Transaction underpriced on goerli

### ISSUE THREAD

**Issue by mariacarmina** [oceanprotocol/ocean.py#1064] opened 2022-11-08 12:38 UTC
On goerli network, it takes too long to fetch the txs due to the fact that are underpriced.
I have tried to set the gas settings from `network-config.yaml` file from brownie and add to
the transaction parameters from each contract call the `priority_fee`, but nothing was changed.

Output:

`    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'} `

**Comment by calina-c** [comment] 2022-11-08 13:56
What is different between this and the issue for polygon?

**Comment by AnaLoznianu** [comment] 2022-11-15 10:46
Closing this as a duplicate of: https://github.com/oceanprotocol/ocean.py/issues/1026

**Closed by AnaLoznianu** 2022-11-15 10:46 UTC
Labels: Type: Bug
