### ISSUE TITLE
Provider nonce handling

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean.py#1446] opened 2023-07-03 13:18 UTC
We have mixed flow of how nonce is used when sending requests to provider.

Some functions are calling getNonce, others are just sending Date.now().

Proposal:

- for all requests, call getNonce()
- increase it by 1
- use the new nonce to sign

**Comment by calina-c** [comment] 2023-08-03 09:15
@alexcos20 is this a duplicate of #1452 (closed last week)?

**Closed** 2023-11-01 06:04 UTC
Labels: Type: Bug, Priority: Critical
