### ISSUE TITLE
Upgrade to ContractCaller interface from ConciseContract which is deprecated

### ISSUE THREAD

**Issue by DMats** [oceanprotocol/ocean.py#346] opened 2021-06-14 16:46 UTC

**Comment by AnaLoznianu** [comment] 2021-06-15 12:42
Closing as is a duplicate of: https://app.zenhub.com/workspaces/backend-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/ocean.py/343

**Closed by AnaLoznianu** 2021-06-15 12:42 UTC
Labels: Status: Duplicate
