### ISSUE TITLE
'Unable to search for DDO` exception when testing ocean assets

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/ocean.py#255] opened 2021-03-26 11:02 UTC
**Describe the bug**
In running `test_ocean_assets.py`, the first two tests fail. 

A snippet of the console log points to something in Aquarius.
```console
E           Exception: Unable to search for DDO: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered
an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the
application.</p>\n'

venv/lib/python3.8/site-packages/ocean_utils/aquarius/aquarius.py:236: Exception
```

Full logs below. I found this while verifying #245.

**To Reproduce**
1. Go through developers.md, up until the pytest section. You could run all of pytest, or just ````pytest ocean_lib/ocean/test/test_ocean_assets.py`
2. See error

Here are the logs:
- [pytest_log.txt](https://github.com/oceanprotocol/ocean.py/files/6211238/pytest_log.txt)
- [barge_log.txt](https://github.com/oceanprotocol/ocean.py/files/6211242/barge_log.txt)

**Expected behavior**
Tests pass.

**Comment by calina-c** [comment] 2021-03-26 13:00
@trentmc I can reproduce this, it's not just a barge update. I'm investigating.

**Comment by calina-c** [comment] 2021-03-26 16:14
will be closed by https://github.com/oceanprotocol/barge/pull/237 but since they are not in the same repo I can't link the PRs

**Comment by calina-c** [comment] 2021-03-29 07:11
Merged on barge and closing.

**Closed by calina-c** 2021-03-29 07:11 UTC
Labels: bug
