### ISSUE TITLE
Provider response download fails when userdata is passed. file_name is None

### ISSUE THREAD

**Issue by jfdelgad** [oceanprotocol/ocean.py#1053] opened 2022-10-27 14:03 UTC
**Describe the bug**
When an onchain asset (function call) is requested, the download fails. The error happens because although the provider returns the contract data, the `file_name` is None.

```
WARNING:ocean_lib.data_provider.base:It was not possible to get the file name. Expected type '<class 'str'>' for attribute 'header' but received type '<class 'NoneType'>')
raise TypeError(TypeError: Expected type '<class 'str'>' for attribute 'file_name' but received type '<class 'NoneType'>')

```

**To Reproduce**
- Download an onchain asset that pass parameters to the function call

**Comment by AnaLoznianu** [comment] 2022-11-01 10:25
@calina-c Can you make sure the fix is included in the brownie branch as well?

**Comment by calina-c** [comment] 2022-11-01 12:46
@jfdelgad it seems to me like this is a duplicate of #1031. Can you confirm? Also, did you do any fix related to the typing error? I can't seem to find it although it was discused in the sprint planning meeting.

**Comment by jfdelgad** [comment] 2022-11-01 13:02
@calina-c This has been already included in the main. There were two things, on change in the ocean provider repo, made by Alex and a change in ocean made by me. The type returned is still NoneType for contract functions with parameters, as Alex indicated that there are not file_name for contract functions, so ocean.py manages this particular situation.

**Comment by jfdelgad** [comment] 2022-11-01 13:52
here is the PR made and merged to main: https://github.com/oceanprotocol/ocean.py/pull/1050

**Comment by calina-c** [comment] 2022-11-05 07:47
Merged to main-brownie: https://github.com/oceanprotocol/ocean.py/pull/1055

**Comment by calina-c** [comment] 2022-11-05 07:47
Closing since the fix is done in both `main` and `main-brownie`.

**Closed by calina-c** 2022-11-05 07:47 UTC
Labels: Type: Bug
