### ISSUE TITLE
Exception: Invalid or unresponsive aquarius url http://172.15.0.5:5000. Root problem: Docker/Barge only runs on Linux

### ISSUE THREAD

**Issue by bballamudi** [oceanprotocol/ocean.py#1313] opened 2023-02-06 02:19 UTC
**Describe the bug**
I followed through the readme instructions for installing ocean-lib. It is with the instructions for local installation of the whole network system I'm encountering with the issue. However, I checked if it is instead running on localhost:5000. It returns `{"plugin":"module","software":"Aquarius","version":"5.0.0"}`

**To Reproduce**
1. Follow through the installation steps outlined in the [readme](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/install.md).
2. Similarly, perform all the excutions outlined in the readme for local installation of barge and other services.
3. It is at the step where you run the below code in the python console as delineated in readmes, that I get the error. 
`from ocean_lib.ocean.ocean import Ocean; ocean = Ocean(config)`
4. Exception: Invalid or unresponsive aquarius url http://172.15.0.5:5000

**Expected behavior**
I am assuming I get successful response.

**Screenshots**
![image](https://user-images.githubusercontent.com/21183667/216864931-a847a6fb-c01a-4597-a29f-df5dd94a0ec1.png)

**Desktop (please complete the following information):**
 - OS: WSL2 (windows 11)
 - Browser: chrome
 - Version: (ocean-lib: '2.0.1', python: '3.10')

**Additional context**
The problem seems to be with aquarius url http://172.15.0.5:5000. Neither am I am able to get HTTP connection to http://172.15.0.4:8030 so as to make data asset. However, I'm able to send get request to both the ports 5000 and 8030 on localhost though. As such, I'm able to get through these issues if change them to localhost instead of 172.15.0.5[4]. Which makes me suspect if I have not configured the installation setting for Brownie or Barge. Please help me fix the issue.

**Comment by qst2** [comment] 2023-02-15 08:00
hello, i had similar problem with running "ocean = Ocean(config)", having timed out on http://172.15.0.5:5000/
i was able to deploy ocean.py stack with barge on WSL2 Docker-Ubuntu container using image https://github.com/cruizba/ubuntu-dind 
https://hub.docker.com/r/cruizba/ubuntu-dind, 
i suggest to expose the ports at the beginning, something like 
docker run -it --privileged --gpus all  -p 8887:8888 ocean_didi to be able to run jupyter or whatever else.

**Comment by grokpronoia** [comment] 2023-02-24 22:49
Having the same issue. Running macOS Ventura v13.1 on an Apple M1 Max

`>>> ocean = Ocean(config)
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1098a1130>, 'Connection to 172.15.0.5 timed out. (connect timeout=30)')': /
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matthewarrow/ocean/venv/lib/python3.9/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/Users/matthewarrow/ocean/venv/lib/python3.9/site-packages/ocean_lib/ocean/ocean.py", line 98, in __init__
    self.assets = OceanAssets(self.config_dict, data_provider)
  File "/Users/matthewarrow/ocean/venv/lib/python3.9/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/Users/matthewarrow/ocean/venv/lib/python3.9/site-packages/ocean_lib/ocean/ocean_assets.py", line 60, in __init__
    self._aquarius = Aquarius.get_instance(self._metadata_cache_uri)
  File "/Users/matthewarrow/ocean/venv/lib/python3.9/site-packages/ocean_lib/aquarius/aquarius.py", line 55, in get_instance
    return cls(metadata_cache_uri)
  File "/Users/matthewarrow/ocean/venv/lib/python3.9/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/Users/matthewarrow/ocean/venv/lib/python3.9/site-packages/ocean_lib/aquarius/aquarius.py", line 45, in __init__
    raise Exception(f"Invalid or unresponsive aquarius url {aquarius_url}")
Exception: Invalid or unresponsive aquarius url http://172.15.0.5:5000`

**Comment by graceful-coder** [comment] 2023-03-03 19:41
I am also having this issue on 
OS: MacOS Ventura 13.2.1
Chip: Apple M1
Python: 3.10.4
Ocean v4

![aquarius-issue](https://user-images.githubusercontent.com/101472818/222811568-1339053b-9bca-46d3-8f08-150920c44177.png)

**Comment by mariacarmina** [comment] 2023-03-06 13:42
do you have some logs from barge? it's possible that on certain OSes barge does not run properly.

**Comment by alexcos20** [comment] 2023-03-06 14:15
barge was designed for linux.  it MAY work on other platforms, but there are no guarantees.
Based on your OS/docker config, you may find aqua at 172.15.0.5:5000 or localhost:5000, or both.
So, you should define all the urls before running ocean.py (or ocean.py should allow you to do that)

**Comment by mariacarmina** [comment] 2023-03-06 14:26
For setting up the URLs, [this README](https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/parameters.md) can help

**Comment by graceful-coder** [comment] 2023-03-06 16:43
When I modified the METADATA_CACHE_URI and PROVIDER_URL in the config dictionary to point to the following:    'METADATA_CACHE_URI': "https://v4.aquarius.oceanprotocol.com",
   'PROVIDER_URL' : "https://v4.provider.goerli.oceanprotocol.com"

It resolves the unresponsive Aquarius URL error, but then when following main-flow.md the ddo holding the metadata appears empty when publishing a dataset. In the attached screenshots you can see an unsupported chain ID error in the barge logs.
![ddo-barge-log](https://user-images.githubusercontent.com/101472818/223174380-0c0d7324-007e-4eab-866b-d4c65488476a.png)
![NoneType-ddo](https://user-images.githubusercontent.com/101472818/223174394-9ff0a84c-49e7-4f52-a7ab-b2c3c2c5350e.png)

**Comment by graceful-coder** [comment] 2023-03-06 18:57
Providing one more screenshot - at the bottom you can see a subgraph not defined for 8996 error. 
![Screenshot 2023-03-06 at 1 36 42 PM](https://user-images.githubusercontent.com/101472818/223204644-f442cf93-1f8a-45fb-818d-bd81a32786c6.png)

**Comment by trentmc** [comment] 2023-03-20 09:21
> barge was designed for linux. it MAY work on other platforms, but there are no guarantees.

To support local setup on Mac or Win, here's another potential approach: don't use Docker. Instead, have the user run individual components.

Specifically, have the user...
- in a new terminal: install ganache, set needed envvars, and launch it
- in a new terminal: `git clone` Provider, set needed envvars, and launch it
- in a new terminal: `git clone` Aquarius, set needed envvars, and launch it

We actually had it like this in the early days of ocean.py right after Ocean V3 was launched (fall 2020). But to streamline user onboarding, we switched over to barge to collect all of the above into a single command. So if we did do it for this github issue, I'd recommend to keep it streamlined for linux users.

That is, the [top-level README](https://github.com/oceanprotocol/ocean.py#readme) would look something like:

--
Follow these steps in sequence to ramp into Ocean.

 1. **Install Ocean**
 2. **Setup:**
    - **Remote** (Win, MacOS, Linux) --> goes to setup-remote.md
    - *or* **Local-Linux)** (Linux only) --> goes to setup-local-linux.md
    - *or* **Local-other** (Mac, Windows) --> goes to setup-local-other.md
 3. **Walk through main flow**: publish asset, post for free / for sale, dispense it / buy it, and consume it

--

**Comment by graceful-coder** [comment] 2023-03-31 12:58
Closing because users can use setup-remote.md to avoid Barge and the README is updated accordingly. Definitive fix will be in #1353.

**Closed by graceful-coder** 2023-03-31 12:58 UTC
Labels: Type: Bug, Priority: High

**Comment by trentmc** [comment] 2023-04-04 12:33
Also: this issue will help: https://github.com/oceanprotocol/pm/issues/191 "Docker images for multiple platforms"
